import { describe, it, expect } from 'vitest';
import { generateExecutiveReport } from '../../src/utils/report-generator';
import { generateWebMetrics, generateSeoMetrics, generateEmailMetrics, generateCrmMetrics, generateMartechHealth } from '../../src/utils/mock-generator';

const reportData = {
  web: generateWebMetrics(),
  seo: generateSeoMetrics(),
  email: generateEmailMetrics(),
  crm: generateCrmMetrics(),
  martech: generateMartechHealth(),
};

describe('generateExecutiveReport', () => {
  const report = generateExecutiveReport(reportData);

  it('returns a non-empty string', () => {
    expect(report).toBeTruthy();
    expect(typeof report).toBe('string');
  });

  it('includes report header with date', () => {
    expect(report).toContain('# GrowthHQ Executive Report');
    expect(report).toContain('Period: Last 30 days');
  });

  it('includes all major sections', () => {
    expect(report).toContain('## Web Performance');
    expect(report).toContain('## SEO Performance');
    expect(report).toContain('## Email Marketing');
    expect(report).toContain('## CRM Pipeline');
    expect(report).toContain('## Martech Health');
  });

  it('includes channel mix table', () => {
    expect(report).toContain('### Channel Mix');
    expect(report).toContain('organic');
  });

  it('includes top queries', () => {
    expect(report).toContain('### Top 5 Queries');
  });

  it('includes channel attribution', () => {
    expect(report).toContain('### Channel Attribution');
    expect(report).toContain('Organic Search');
  });

  it('includes funnel stages', () => {
    expect(report).toContain('Leads');
    expect(report).toContain('MQL');
    expect(report).toContain('Win Rate');
  });

  it('includes martech system table', () => {
    expect(report).toMatch(/\| .+ \| (healthy|degraded|down) \|/);
  });

  it('includes insights section', () => {
    expect(report).toContain('## Key Insights');
  });

  it('ends with footer', () => {
    expect(report).toContain('Generated by GrowthHQ');
  });
});
